# انتخاب تصویر پایه Node.js
FROM node:20

# مشخص کردن مسیر کاری داخل کانتینر
WORKDIR /usr/src/frontend

# کپی محتویات فولدر frontend به داخل کانتینر
COPY frontend/package*.json ./
COPY frontend/. ./

# نصب dependencies
RUN npm install

# پورت پیش‌فرض React
EXPOSE 3000

# اجرای پروژه در حالت توسعه
CMD ["npm", "run","dev"]