# Generated by Django 4.2 on 2025-09-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramprofile',
            name='media_count',
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='instagramprofile',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
    ]
