# Generated by Django 4.2 on 2025-09-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_remove_instagramprofile_media_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramprofile',
            name='campaign',
            field=models.CharField(default='بدون نام', max_length=255, verbose_name='کمپین'),
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='content',
            field=models.TextField(default='بدون محتوا', verbose_name='متن پست'),
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='platforms',
            field=models.JSONField(default=list, verbose_name='پلتفرم\u200cها'),
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('scheduled', 'زمان\u200cبندی\u200cشده'), ('published', 'منتشر شده'), ('failed', 'ناموفق')], default='draft', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='tags',
            field=models.JSONField(default=list, verbose_name='تگ\u200cها'),
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='total_comments',
            field=models.IntegerField(default=0, verbose_name='تعداد کامنت\u200cها'),
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='total_saves',
            field=models.IntegerField(default=0, verbose_name='تعداد سیو/ذخیره'),
        ),
        migrations.AddField(
            model_name='instagramprofile',
            name='total_shares',
            field=models.IntegerField(default=0, verbose_name='تعداد شیر/بازنشر'),
        ),
        migrations.AlterField(
            model_name='instagramprofile',
            name='created_date',
            field=models.DateTimeField(verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='instagramprofile',
            name='followers_count',
            field=models.IntegerField(default=0, verbose_name='تعداد فالوورها'),
        ),
        migrations.AlterField(
            model_name='instagramprofile',
            name='total_likes',
            field=models.IntegerField(default=0, verbose_name='مجموع لایک\u200cها'),
        ),
        migrations.AlterField(
            model_name='instagramprofile',
            name='total_views',
            field=models.IntegerField(default=0, verbose_name='مجموع بازدیدها'),
        ),
        migrations.AlterField(
            model_name='instagramprofile',
            name='updated_date',
            field=models.DateTimeField(verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='instagramprofile',
            name='username',
            field=models.CharField(max_length=255, verbose_name='نام کاربری'),
        ),
    ]
