# Generated by Django 4.2 on 2025-09-14 20:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_instagramprofile_campaign_instagramprofile_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramprofile',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='instagramprofile',
            name='content',
        ),
        migrations.RemoveField(
            model_name='instagramprofile',
            name='platforms',
        ),
        migrations.RemoveField(
            model_name='instagramprofile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='instagramprofile',
            name='tags',
        ),
        migrations.AlterField(
            model_name='instagramprofile',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='instagramprofile',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.CharField(default='بدون نام', max_length=255, verbose_name='کمپین')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('scheduled', 'زمان\u200cبندی\u200cشده'), ('published', 'منتشر شده'), ('failed', 'ناموفق')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('content', models.TextField(default='بدون محتوا', verbose_name='متن پست')),
                ('platforms', models.JSONField(default=list, verbose_name='پلتفرم\u200cها')),
                ('tags', models.JSONField(default=list, verbose_name='تگ\u200cها')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ بروزرسانی')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='instagram.instagramprofile', verbose_name='پروفایل')),
            ],
        ),
    ]
