# Generated by Django 4.2 on 2025-09-15 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_remove_instagramprofile_campaign_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='instagram.instagramprofile', verbose_name='پروفایل'),
        ),
    ]
