# Generated by Django 4.2 on 2025-09-20 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0005_alter_instagrampost_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='کاربر')),
                ('type', models.CharField(choices=[('like', 'لایک'), ('comment', 'کامنت'), ('share', 'اشتراک\u200cگذاری'), ('save', 'ذخیره'), ('view', 'بازدید')], max_length=20, verbose_name='نوع تعامل')),
                ('content', models.TextField(blank=True, null=True, verbose_name='محتوای تعامل (مثلا متن کامنت)')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='زمان تعامل')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='<UNK> <UNK>')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='instagram.instagrampost', verbose_name='پست')),
            ],
        ),
    ]
