# Generated by Django 4.2 on 2025-09-14 20:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام صفحه')),
                ('followers_count', models.IntegerField(default=0, verbose_name='تعداد فالوورها')),
                ('total_likes', models.IntegerField(default=0, verbose_name='مجموع لایک\u200cها')),
                ('total_views', models.IntegerField(default=0, verbose_name='مجموع بازدیدها')),
                ('total_comments', models.IntegerField(default=0, verbose_name='تعداد کامنت\u200cها')),
                ('total_shares', models.IntegerField(default=0, verbose_name='تعداد شیر/بازنشر')),
                ('total_saves', models.IntegerField(default=0, verbose_name='تعداد سیو/ذخیره')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ بروزرسانی')),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.CharField(default='بدون نام', max_length=255, verbose_name='کمپین')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('scheduled', 'زمان\u200cبندی\u200cشده'), ('published', 'منتشر شده'), ('failed', 'ناموفق')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('content', models.TextField(default='بدون محتوا', verbose_name='متن پست')),
                ('platforms', models.JSONField(default=list, verbose_name='پلتفرم\u200cها')),
                ('tags', models.JSONField(default=list, verbose_name='تگ\u200cها')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ایجاد')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ بروزرسانی')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='facebook.facebookprofile', verbose_name='پروفایل')),
            ],
        ),
    ]
