# Generated by Django 4.2 on 2025-09-20 10:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_alter_youtubevideomodel_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, verbose_name='کاربر')),
                ('type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('share', 'Share'), ('view', 'View'), ('save', 'Save')], max_length=20, verbose_name='نوع تعامل')),
                ('content', models.TextField(blank=True, null=True, verbose_name='محتوا/کامنت')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='youtube.youtubevideomodel')),
            ],
        ),
    ]
